name: Build LuckPerms

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name : Build with Gradle
        run: |
          chmod -R +x gradlew
          ./gradlew build --no-daemon --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LuckPerms-${{ github.run_number }}
          path: |
            bukkit/loader/build/libs/LuckPerms-Bukkit-**.jar
            velocity/build/libs/LuckPerms-Velocity-**.jar